const actions = {
  SET_FIELD: 'SET_FIELD',
  RESET_FIELDS: 'RESET_FIELDS',
  RESET_LISTS: 'RESET_LISTS',
  SET_TOKEN: 'SET_TOKEN',
  GET_RECOMMENDATIONS: 'GET_RECOMMENDATIONS',
  GET_ALBUMS: 'GET_ALBUMS',
  GET_ALBUM_BY_ID: 'GET_ALBUM_BY_ID'
};

export default actions;
